ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS fiber DOUBLE PRECISION;
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS sugars DOUBLE PRECISION;
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS sodium DOUBLE PRECISION;
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS potassium DOUBLE PRECISION;
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS calcium DOUBLE PRECISION;
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS iron DOUBLE PRECISION;
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS vitamin_c DOUBLE PRECISION;
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS vitamin_a DOUBLE PRECISION;
